[postgres.credentials]
username = "postgres"
password = "postgres_password
database = "fxrate_db"
host = "localhost"
port = 5432

[fxrate_pipeline.destination.postgres.credentials]
username = "postgres"
password = "postgres_password"
database = "fxrate_db"
host = "localhost"
port = 5432